export interface GetAllUserResponse {
    userId: string,
    firstName: string,
    lastName: string,
    emailAddress: string,
    departmentCode: string,
    departmentName: string,
    jobCode: string,
    jobRole: string,
    group1Name: string,
    group2Name: string,
    group3Name: string,
    group4Name: string,
    group5Name: string,
    status: boolean,
    loginId: string,
    contactNumber: string,
    zipCode: string,
    displayStatus: string,
    departmentId: string,
    jobCodeId: string,
    isSuccess: boolean,
}
