
export interface UserByIDResponse {
    userId: string,
    firstName: string,
    lastName: string,
    emailAddress: string,
    loginId: string,
    contactNumber: string,
    hiringDate: Date | null,
    zipCode: string,
    status: boolean,
    departmentId: string,
    jobCodeId: string,
    roleChangeDate: Date | null,
    timeZoneId: string,
    profilePic: string,
    groupId: string,
    countryId: string,
    stateId: string,
    cityId: string,
    group1Name: string,
    group2Name: string,
    group3Name: string,
    group4Name: string,
    group5Name: string,
    isSuccess: boolean,
    totalCount: number,
    createdDateDisplay: string,
    lastModifiedDateDisplay: string
}