import LoadableComponent from './../Loadable/index';

export const userRouter: any = [
    {
        path: '/user',
        name: 'user',
        title: 'User',
        component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
        isLayout: true,
        showInMenu: false,
    },
    {
        path: '/user/login',
        name: 'login',
        title: 'LogIn',
        component: LoadableComponent(() => import('../../scenes/Login')),
        showInMenu: false,
    },
];

export const appRouters: any = [
    {
        path: '/',
        exact: true,
        name: 'home',
        title: 'Home',
        icon: 'home',
        component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
        isLayout: true,
        showInMenu: false,
        parentFeatureId : ''
    },

    {
        featureId: 'Dashboard',
        title: 'Dashboard',
        name: 'Dashboard',
        path: '/dashboard',
        parentFeatureId: '',
        className: 'dashboardmenuicon',
        showInMenu: true,
        displayOrder: 0,
        component: LoadableComponent(() => import('../../scenes/Dashboard')),
    },
    
    {
        featureId: 'UserManagement',
        title: 'Users',
        name: 'User Management',
        path: '/users',
        parentFeatureId: '',
        className: 'usermenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    {
        featureId: 'ContentManagement',
        title: 'Content Repository',
        name: 'Content Repository',
        path: '#',
        parentFeatureId: '',
        className: 'contrepomenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    {
        featureId: 'AssignmentRules',
        title: 'AssignmentRules',
        name: 'AssignmentRules',
        path: '#',
        parentFeatureId: '',
        className: 'contrepomenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    
    {
        featureId: 'SystemLogs',
        title: 'System Logs',
        name: 'SystemLogs',
        path: '#',
        parentFeatureId: '',
        className: 'contrepomenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    {
        featureId: 'AddEditCourse',
        title: 'Add Course',
        name: 'ManageUsers',
        path: '#',
        parentFeatureId: 'ContentManagement',
        className: 'groupmenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    {
      featureId: 'ManageUsers',
        title: 'Manage Users',
        name: 'ManageUsers',
        path: '/users',
        parentFeatureId: 'UserManagement',
        className: 'groupmenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    {
        featureId: 'ErrorLogs',
          title: 'Error Logs',
          name: 'ErrorLogs',
          path: '#',
          parentFeatureId: 'SystemLogs',
          className: 'groupmenuicon',
          showInMenu: true,
          displayOrder: 1,
          component: LoadableComponent(() => import('../../scenes/Users')),
      },
      {
        featureId: 'BulkImportHistory',
        title: 'Bulk Import History',
        name: 'BulkImportHistory',
        path: '#',
        parentFeatureId: 'UserManagement',
        className: 'contrepomenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    
    {
        featureId: 'EmailLogs',
        title: 'Email Logs',
        name: 'EmailLogs',
        path: '#',
        parentFeatureId: 'SystemLogs',
        className: 'groupmenuicon',
        showInMenu: true,
        displayOrder: 1,
        component: LoadableComponent(() => import('../../scenes/Users')),
    },
    {
        path: '/logout',
        title: 'Logout',
        name: 'logout',
        icon: 'info-circle',
        showInMenu: false,
        component: LoadableComponent(() => import('../../components/Logout')),
    },
    {
        path: '/exception',
        title: 'exception',
        name: 'exception',
        icon: 'info-circle',
        showInMenu: false,
        component: LoadableComponent(() => import('../../scenes/Exception')),
    },
];

export const routers = [...userRouter, ...appRouters];
